import { seedCategories } from "../data/seed-categories.mjs";
import { seedReports } from "../data/seed-reports.mjs";
import { seedStatuses } from "../data/seed-statuses.mjs";
import {
  loadReportHistory,
  loadReportOverrides,
  loadRuntimeReports,
  saveReportHistory,
  saveReportOverrides,
  saveRuntimeReports
} from "./runtime-report-store.mjs";

const ALLOWED_PRIORITIES = new Set(["low", "normal", "high", "urgent"]);
const FORBIDDEN_CREATE_FIELDS = ["id", "status", "createdAt", "updatedAt"];
const ALLOWED_CREATE_FIELDS = new Set([
  "title",
  "description",
  "category",
  "locationText",
  "neighborhood",
  "zone",
  "source",
  "priority",
  "evidenceCount",
  "citizenAlias",
  "contactPhone",
  "locationPrecision",
  "privacyNoticeVersion",
  "privacyAcknowledged",
  "privacyAcknowledgedAt",
  "sensitiveDataConsent"
]);
const ALLOWED_LOCATION_PRECISIONS = new Set(["approximate", "precise"]);
const ALLOWED_STATUS_UPDATE_FIELDS = new Set(["status", "note"]);
const HISTORY_EVENT_TYPES = new Set(["status_change", "internal_note"]);
const HISTORY_ACTOR = "local_admin";
export const PRIVACY_NOTICE_VERSION = "mvp-1";
export const INTERNAL_NOTE_MAX_LENGTH = 500;

function normalize(value) {
  return String(value || "").trim().toLowerCase();
}

function cleanString(value) {
  return typeof value === "string" ? value.trim() : "";
}

function hasText(value) {
  return typeof value === "string" && value.trim().length > 0;
}

function categoryMatches(categoryRecord, category) {
  const target = normalize(category);

  return [categoryRecord.id, categoryRecord.name, categoryRecord.slug]
    .filter(Boolean)
    .some((value) => normalize(value) === target);
}

function findCategory(category) {
  return seedCategories.find((categoryRecord) => categoryMatches(categoryRecord, category));
}

function matchesCategory(report, category) {
  const target = normalize(category);
  const categoryRecord = seedCategories.find((item) => item.slug === report.category);

  return [
    report.category,
    categoryRecord?.id,
    categoryRecord?.name,
    categoryRecord?.slug
  ]
    .filter(Boolean)
    .some((value) => normalize(value) === target);
}

function matchesStatus(report, status) {
  const target = normalize(status);
  const statusRecord = seedStatuses.find((item) => item.slug === report.status);

  return [report.status, statusRecord?.id, statusRecord?.name, statusRecord?.slug]
    .filter(Boolean)
    .some((value) => normalize(value) === target);
}

function statusExists(status) {
  return seedStatuses.some((item) => item.slug === status);
}

function isValidIsoDate(value) {
  return typeof value === "string" && !Number.isNaN(Date.parse(value));
}

function countBy(items, key) {
  return items.reduce((accumulator, item) => {
    const value = item[key];
    accumulator[value] = (accumulator[value] || 0) + 1;
    return accumulator;
  }, {});
}

function applyReportOverrides(reports) {
  const overridesByReport = new Map();

  for (const override of loadReportOverrides()) {
    overridesByReport.set(override.reportId, override);
  }

  return reports.map((report) => {
    const override = overridesByReport.get(report.id);

    if (!override) {
      return report;
    }

    return {
      ...report,
      status: override.status,
      updatedAt: override.updatedAt,
      adminStatusUpdatedAt: override.updatedAt
    };
  });
}

function rawReports() {
  return [...seedReports, ...loadRuntimeReports()];
}

function allReports() {
  return applyReportOverrides(rawReports());
}

function nextReportId() {
  const suffix = `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
  return `report-local-${suffix}`;
}

function nextHistoryEventId() {
  const suffix = `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
  return `history-local-${suffix}`;
}

function validateLength(errors, field, value, min, max) {
  if (value.length < min || value.length > max) {
    errors.push({
      field,
      message: `${field} must be between ${min} and ${max} characters.`
    });
  }
}

function validatePhone(value) {
  return /^[0-9 +().-]{7,30}$/.test(value);
}

export function validateReportInput(input) {
  const errors = [];

  if (!input || typeof input !== "object" || Array.isArray(input)) {
    return {
      ok: false,
      errors: [
        {
          field: "body",
          message: "Request body must be a JSON object."
        }
      ]
    };
  }

  for (const field of FORBIDDEN_CREATE_FIELDS) {
    if (Object.hasOwn(input, field)) {
      errors.push({
        field,
        message: `${field} is generated by the platform and cannot be provided.`
      });
    }
  }

  for (const field of Object.keys(input)) {
    if (!ALLOWED_CREATE_FIELDS.has(field) && !FORBIDDEN_CREATE_FIELDS.includes(field)) {
      errors.push({
        field,
        message: `${field} is not accepted for local report creation.`
      });
    }
  }

  const title = cleanString(input.title);
  const description = cleanString(input.description);
  const categoryValue = cleanString(input.category);
  const locationText = cleanString(input.locationText);
  const neighborhood = cleanString(input.neighborhood);
  const zone = cleanString(input.zone);
  const citizenAlias = cleanString(input.citizenAlias) || "Ciudadano anonimo";
  const contactPhone = cleanString(input.contactPhone);
  const source = cleanString(input.source) || "manual";
  const priority = cleanString(input.priority) || "normal";
  const locationPrecision = cleanString(input.locationPrecision) || "approximate";
  const evidenceCount = input.evidenceCount === undefined ? 0 : input.evidenceCount;
  const category = findCategory(categoryValue);
  const hasPhone = Boolean(contactPhone);
  const hasPreciseLocation = locationPrecision === "precise";
  const hasEvidence = Number.isInteger(evidenceCount) && evidenceCount > 0;
  const hasSensitiveOptionalData = hasPhone || hasPreciseLocation || hasEvidence;

  if (!title) {
    errors.push({ field: "title", message: "title is required." });
  } else {
    validateLength(errors, "title", title, 5, 120);
  }

  if (!description) {
    errors.push({ field: "description", message: "description is required." });
  } else {
    validateLength(errors, "description", description, 15, 1000);
  }

  if (!categoryValue) {
    errors.push({ field: "category", message: "category is required." });
  } else if (!category) {
    errors.push({ field: "category", message: "category must match an existing category." });
  }

  if (!locationText) {
    errors.push({ field: "locationText", message: "locationText is required." });
  } else {
    validateLength(errors, "locationText", locationText, 5, 200);
  }

  if (!neighborhood && !zone) {
    errors.push({
      field: "neighborhood",
      message: "neighborhood or zone is required."
    });
  }

  if (neighborhood) {
    validateLength(errors, "neighborhood", neighborhood, 2, 120);
  }

  if (zone) {
    validateLength(errors, "zone", zone, 2, 120);
  }

  if (contactPhone && !validatePhone(contactPhone)) {
    errors.push({
      field: "contactPhone",
      message: "contactPhone must be a local optional phone reference with 7 to 30 valid characters."
    });
  }

  if (!ALLOWED_LOCATION_PRECISIONS.has(locationPrecision)) {
    errors.push({
      field: "locationPrecision",
      message: "locationPrecision must be approximate or precise."
    });
  }

  if (!ALLOWED_PRIORITIES.has(priority)) {
    errors.push({
      field: "priority",
      message: "priority must be one of low, normal, high or urgent."
    });
  }

  if (!Number.isInteger(evidenceCount) || evidenceCount < 0 || evidenceCount > 20) {
    errors.push({
      field: "evidenceCount",
      message: "evidenceCount must be an integer from 0 to 20."
    });
  }

  if (input.privacyAcknowledged !== true) {
    errors.push({
      field: "privacyAcknowledged",
      message: "privacyAcknowledged must be true before creating a local report."
    });
  }

  if (input.privacyNoticeVersion !== PRIVACY_NOTICE_VERSION) {
    errors.push({
      field: "privacyNoticeVersion",
      message: `privacyNoticeVersion must be ${PRIVACY_NOTICE_VERSION}.`
    });
  }

  if (Object.hasOwn(input, "privacyAcknowledgedAt") && !hasText(input.privacyAcknowledgedAt)) {
    errors.push({
      field: "privacyAcknowledgedAt",
      message: "privacyAcknowledgedAt must not be an empty value when provided."
    });
  }

  if (Object.hasOwn(input, "sensitiveDataConsent") && typeof input.sensitiveDataConsent !== "boolean") {
    errors.push({
      field: "sensitiveDataConsent",
      message: "sensitiveDataConsent must be true or false."
    });
  }

  if (hasSensitiveOptionalData && input.sensitiveDataConsent !== true) {
    errors.push({
      field: "sensitiveDataConsent",
      message: "sensitiveDataConsent must be true when phone, precise location or evidence is provided."
    });
  }

  if (citizenAlias.length > 80) {
    errors.push({
      field: "citizenAlias",
      message: "citizenAlias must be 80 characters or fewer."
    });
  }

  if (source !== "manual") {
    errors.push({
      field: "source",
      message: "source must be manual for locally created reports."
    });
  }

  if (errors.length > 0) {
    return {
      ok: false,
      errors
    };
  }

  return {
    ok: true,
    value: {
      title,
      description,
      category: category.slug,
      priority,
      locationText,
      neighborhood: neighborhood || zone,
      zone: zone || neighborhood,
      source: "manual",
      evidenceCount,
      citizenAlias,
      ...(contactPhone ? { contactPhone } : {}),
      locationPrecision,
      privacyNoticeVersion: PRIVACY_NOTICE_VERSION,
      privacyAcknowledged: true,
      sensitiveDataConsent: hasSensitiveOptionalData ? true : input.sensitiveDataConsent === true,
      containsSensitiveOptionalData: hasSensitiveOptionalData
    }
  };
}

export function validateStatusUpdateInput(input) {
  const errors = [];

  if (!input || typeof input !== "object" || Array.isArray(input)) {
    return {
      ok: false,
      errors: [
        {
          field: "body",
          message: "Request body must be a JSON object."
        }
      ]
    };
  }

  for (const field of Object.keys(input)) {
    if (!ALLOWED_STATUS_UPDATE_FIELDS.has(field)) {
      errors.push({
        field,
        message: `${field} cannot be updated in this task. Only status and note are allowed.`
      });
    }
  }

  let status;
  let note;

  if (Object.hasOwn(input, "status")) {
    if (typeof input.status !== "string") {
      errors.push({
        field: "status",
        message: "status must be text."
      });
    } else {
      status = cleanString(input.status);

      if (!status) {
        errors.push({
          field: "status",
          message: "status cannot be empty."
        });
      } else if (!statusExists(status)) {
        errors.push({
          field: "status",
          message: "status must match an existing platform status."
        });
      }
    }
  }

  if (Object.hasOwn(input, "note")) {
    if (typeof input.note !== "string") {
      errors.push({
        field: "note",
        message: "note must be text."
      });
    } else {
      note = cleanString(input.note);

      if (!note) {
        errors.push({
          field: "note",
          message: "note cannot be empty."
        });
      } else if (note.length > INTERNAL_NOTE_MAX_LENGTH) {
        errors.push({
          field: "note",
          message: `note must be ${INTERNAL_NOTE_MAX_LENGTH} characters or fewer.`
        });
      }
    }
  }

  if (!Object.hasOwn(input, "status") && !Object.hasOwn(input, "note")) {
    errors.push({
      field: "body",
      message: "Request body must include status or note."
    });
  }

  if (errors.length > 0) {
    return {
      ok: false,
      errors
    };
  }

  return {
    ok: true,
    value: {
      ...(status ? { status } : {}),
      ...(note ? { note } : {})
    }
  };
}

export const validateReportStatusUpdate = validateStatusUpdateInput;

export function validateStoredHistoryEvent(event) {
  const errors = [];

  if (!event || typeof event !== "object" || Array.isArray(event)) {
    return {
      ok: false,
      errors: [{ field: "event", message: "History event must be an object." }]
    };
  }

  if (typeof event.id !== "string" || !event.id.trim()) {
    errors.push({ field: "id", message: "History event id must be text." });
  }

  if (typeof event.reportId !== "string" || !event.reportId.trim()) {
    errors.push({ field: "reportId", message: "History event reportId must be text." });
  }

  if (!HISTORY_EVENT_TYPES.has(event.type)) {
    errors.push({ field: "type", message: "History event type is not supported." });
  }

  if (!isValidIsoDate(event.createdAt)) {
    errors.push({ field: "createdAt", message: "History event createdAt must be ISO 8601." });
  }

  if (event.actor !== HISTORY_ACTOR) {
    errors.push({ field: "actor", message: "History event actor must be local_admin." });
  }

  if (event.note !== undefined) {
    if (typeof event.note !== "string") {
      errors.push({ field: "note", message: "History event note must be text." });
    } else if (event.note.length > INTERNAL_NOTE_MAX_LENGTH) {
      errors.push({
        field: "note",
        message: `History event note must be ${INTERNAL_NOTE_MAX_LENGTH} characters or fewer.`
      });
    }
  }

  if (event.type === "status_change") {
    if (!statusExists(event.previousStatus)) {
      errors.push({ field: "previousStatus", message: "History event previousStatus is invalid." });
    }

    if (!statusExists(event.newStatus)) {
      errors.push({ field: "newStatus", message: "History event newStatus is invalid." });
    }
  }

  if (event.type === "internal_note") {
    if (typeof event.note !== "string" || !event.note.trim()) {
      errors.push({ field: "note", message: "Internal note history events require note text." });
    }

    if (event.previousStatus !== undefined || event.newStatus !== undefined) {
      errors.push({
        field: "status",
        message: "Internal note history events must not include status transitions."
      });
    }
  }

  if (errors.length > 0) {
    return {
      ok: false,
      errors
    };
  }

  return {
    ok: true,
    event
  };
}

function validatedReportHistory() {
  const events = loadReportHistory();

  for (const event of events) {
    const validation = validateStoredHistoryEvent(event);

    if (!validation.ok) {
      throw new Error("Report history file contains invalid events.");
    }
  }

  return events;
}

function appendHistoryEvent(event) {
  const events = validatedReportHistory();
  saveReportHistory([...events, event]);
}

export function listReportHistory(reportId) {
  return validatedReportHistory()
    .filter((event) => event.reportId === reportId)
    .sort((left, right) => {
      const byDate = left.createdAt.localeCompare(right.createdAt);
      return byDate === 0 ? left.id.localeCompare(right.id) : byDate;
    });
}

export function createInternalNote(reportId, note, options = {}) {
  const now = options.now || new Date().toISOString();

  return {
    id: options.eventId || nextHistoryEventId(),
    reportId,
    type: "internal_note",
    createdAt: now,
    actor: HISTORY_ACTOR,
    note
  };
}

export function createStatusChangeEvent(reportId, previousStatus, newStatus, note, options = {}) {
  const now = options.now || new Date().toISOString();

  return {
    id: options.eventId || nextHistoryEventId(),
    reportId,
    type: "status_change",
    createdAt: now,
    actor: HISTORY_ACTOR,
    ...(note ? { note } : {}),
    previousStatus,
    newStatus
  };
}

export function listCategories() {
  return seedCategories;
}

export function listStatuses() {
  return seedStatuses;
}

export function listReports(filters = {}) {
  return allReports().filter((report) => {
    if (filters.category && !matchesCategory(report, filters.category)) {
      return false;
    }

    if (filters.status && !matchesStatus(report, filters.status)) {
      return false;
    }

    return true;
  });
}

export function getReportById(id) {
  return allReports().find((report) => report.id === id);
}

export function listReportsByCategory(category) {
  return listReports({ category });
}

export function listReportsByStatus(status) {
  return listReports({ status });
}

export function getReportStats() {
  const reports = allReports();
  const createdDates = reports
    .map((report) => report.createdAt)
    .sort((left, right) => left.localeCompare(right));

  return {
    totalReports: reports.length,
    byCategory: countBy(reports, "category"),
    byStatus: countBy(reports, "status"),
    byPriority: countBy(reports, "priority"),
    newestReportCreatedAt: createdDates.at(-1) || null,
    oldestReportCreatedAt: createdDates[0] || null
  };
}

export function createReport(input, options = {}) {
  const validation = validateReportInput(input);

  if (!validation.ok) {
    return validation;
  }

  const now = options.now || new Date().toISOString();
  const report = {
    id: options.id || nextReportId(),
    ...validation.value,
    ...(options.extraFields || {}),
    source: options.source || validation.value.source,
    privacyAcknowledgedAt: now,
    status: "new",
    createdAt: now,
    updatedAt: now
  };
  const runtimeReports = loadRuntimeReports();

  saveRuntimeReports([...runtimeReports, report]);

  return {
    ok: true,
    report
  };
}

export function updateRuntimeReportFields(id, fields, options = {}) {
  const now = options.now || new Date().toISOString();
  const runtimeReports = loadRuntimeReports();
  const index = runtimeReports.findIndex((report) => report.id === id);

  if (index === -1) {
    return {
      ok: false,
      notFound: true,
      id
    };
  }

  const updated = {
    ...runtimeReports[index],
    ...fields,
    updatedAt: now
  };

  runtimeReports[index] = updated;
  saveRuntimeReports(runtimeReports);

  return {
    ok: true,
    report: getReportById(id)
  };
}

export function updateReportStatus(id, input, options = {}) {
  const existingReport = getReportById(id);

  if (!existingReport) {
    return {
      ok: false,
      notFound: true,
      id
    };
  }

  const validation = validateStatusUpdateInput(input);

  if (!validation.ok) {
    return validation;
  }

  const now = options.now || new Date().toISOString();
  const previousStatus = existingReport.status;
  const newStatus = validation.value.status || previousStatus;
  let historyEvent = null;
  let changed = false;

  if (newStatus !== previousStatus) {
    const overrides = loadReportOverrides().filter((override) => override.reportId !== id);
    const override = {
      reportId: id,
      status: newStatus,
      updatedAt: now
    };

    saveReportOverrides([...overrides, override]);
    historyEvent = createStatusChangeEvent(
      id,
      previousStatus,
      newStatus,
      validation.value.note,
      {
        now,
        eventId: options.eventId
      }
    );
    appendHistoryEvent(historyEvent);
    changed = true;
  } else if (validation.value.note) {
    historyEvent = createInternalNote(id, validation.value.note, {
      now,
      eventId: options.eventId
    });
    appendHistoryEvent(historyEvent);
  }

  return {
    ok: true,
    report: getReportById(id),
    historyEvent,
    changed,
    noop: !changed && !historyEvent,
    message:
      !changed && !historyEvent
        ? "No status change or internal note was recorded."
        : "Internal follow-up saved."
  };
}
