import { seedCategories } from "../data/seed-categories.mjs";
import { seedReports } from "../data/seed-reports.mjs";
import { seedStatuses } from "../data/seed-statuses.mjs";
import { loadRuntimeReports, saveRuntimeReports } from "./runtime-report-store.mjs";

const ALLOWED_PRIORITIES = new Set(["low", "normal", "high", "urgent"]);
const FORBIDDEN_CREATE_FIELDS = ["id", "status", "createdAt", "updatedAt"];

function normalize(value) {
  return String(value || "").trim().toLowerCase();
}

function cleanString(value) {
  return typeof value === "string" ? value.trim() : "";
}

function categoryMatches(categoryRecord, category) {
  const target = normalize(category);

  return [categoryRecord.id, categoryRecord.name, categoryRecord.slug]
    .filter(Boolean)
    .some((value) => normalize(value) === target);
}

function findCategory(category) {
  return seedCategories.find((categoryRecord) => categoryMatches(categoryRecord, category));
}

function matchesCategory(report, category) {
  const target = normalize(category);
  const categoryRecord = seedCategories.find((item) => item.slug === report.category);

  return [
    report.category,
    categoryRecord?.id,
    categoryRecord?.name,
    categoryRecord?.slug
  ]
    .filter(Boolean)
    .some((value) => normalize(value) === target);
}

function matchesStatus(report, status) {
  const target = normalize(status);
  const statusRecord = seedStatuses.find((item) => item.slug === report.status);

  return [report.status, statusRecord?.id, statusRecord?.name, statusRecord?.slug]
    .filter(Boolean)
    .some((value) => normalize(value) === target);
}

function countBy(items, key) {
  return items.reduce((accumulator, item) => {
    const value = item[key];
    accumulator[value] = (accumulator[value] || 0) + 1;
    return accumulator;
  }, {});
}

function allReports() {
  return [...seedReports, ...loadRuntimeReports()];
}

function nextReportId() {
  const suffix = `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
  return `report-local-${suffix}`;
}

function validateLength(errors, field, value, min, max) {
  if (value.length < min || value.length > max) {
    errors.push({
      field,
      message: `${field} must be between ${min} and ${max} characters.`
    });
  }
}

export function validateReportInput(input) {
  const errors = [];

  if (!input || typeof input !== "object" || Array.isArray(input)) {
    return {
      ok: false,
      errors: [
        {
          field: "body",
          message: "Request body must be a JSON object."
        }
      ]
    };
  }

  for (const field of FORBIDDEN_CREATE_FIELDS) {
    if (Object.hasOwn(input, field)) {
      errors.push({
        field,
        message: `${field} is generated by the platform and cannot be provided.`
      });
    }
  }

  const title = cleanString(input.title);
  const description = cleanString(input.description);
  const categoryValue = cleanString(input.category);
  const locationText = cleanString(input.locationText);
  const neighborhood = cleanString(input.neighborhood);
  const zone = cleanString(input.zone);
  const citizenAlias = cleanString(input.citizenAlias) || "Ciudadano anonimo";
  const source = cleanString(input.source) || "manual";
  const priority = cleanString(input.priority) || "normal";
  const evidenceCount = input.evidenceCount === undefined ? 0 : input.evidenceCount;
  const category = findCategory(categoryValue);

  if (!title) {
    errors.push({ field: "title", message: "title is required." });
  } else {
    validateLength(errors, "title", title, 5, 120);
  }

  if (!description) {
    errors.push({ field: "description", message: "description is required." });
  } else {
    validateLength(errors, "description", description, 15, 1000);
  }

  if (!categoryValue) {
    errors.push({ field: "category", message: "category is required." });
  } else if (!category) {
    errors.push({ field: "category", message: "category must match an existing category." });
  }

  if (!locationText) {
    errors.push({ field: "locationText", message: "locationText is required." });
  } else {
    validateLength(errors, "locationText", locationText, 5, 200);
  }

  if (!neighborhood && !zone) {
    errors.push({
      field: "neighborhood",
      message: "neighborhood or zone is required."
    });
  }

  if (neighborhood) {
    validateLength(errors, "neighborhood", neighborhood, 2, 120);
  }

  if (zone) {
    validateLength(errors, "zone", zone, 2, 120);
  }

  if (!ALLOWED_PRIORITIES.has(priority)) {
    errors.push({
      field: "priority",
      message: "priority must be one of low, normal, high or urgent."
    });
  }

  if (!Number.isInteger(evidenceCount) || evidenceCount < 0 || evidenceCount > 20) {
    errors.push({
      field: "evidenceCount",
      message: "evidenceCount must be an integer from 0 to 20."
    });
  }

  if (citizenAlias.length > 80) {
    errors.push({
      field: "citizenAlias",
      message: "citizenAlias must be 80 characters or fewer."
    });
  }

  if (source !== "manual") {
    errors.push({
      field: "source",
      message: "source must be manual for locally created reports."
    });
  }

  if (errors.length > 0) {
    return {
      ok: false,
      errors
    };
  }

  return {
    ok: true,
    value: {
      title,
      description,
      category: category.slug,
      priority,
      locationText,
      neighborhood: neighborhood || zone,
      zone: zone || neighborhood,
      source: "manual",
      evidenceCount,
      citizenAlias
    }
  };
}

export function listCategories() {
  return seedCategories;
}

export function listStatuses() {
  return seedStatuses;
}

export function listReports(filters = {}) {
  return allReports().filter((report) => {
    if (filters.category && !matchesCategory(report, filters.category)) {
      return false;
    }

    if (filters.status && !matchesStatus(report, filters.status)) {
      return false;
    }

    return true;
  });
}

export function getReportById(id) {
  return allReports().find((report) => report.id === id);
}

export function listReportsByCategory(category) {
  return listReports({ category });
}

export function listReportsByStatus(status) {
  return listReports({ status });
}

export function getReportStats() {
  const reports = allReports();
  const createdDates = reports
    .map((report) => report.createdAt)
    .sort((left, right) => left.localeCompare(right));

  return {
    totalReports: reports.length,
    byCategory: countBy(reports, "category"),
    byStatus: countBy(reports, "status"),
    byPriority: countBy(reports, "priority"),
    newestReportCreatedAt: createdDates.at(-1) || null,
    oldestReportCreatedAt: createdDates[0] || null
  };
}

export function createReport(input, options = {}) {
  const validation = validateReportInput(input);

  if (!validation.ok) {
    return validation;
  }

  const now = options.now || new Date().toISOString();
  const report = {
    id: options.id || nextReportId(),
    ...validation.value,
    status: "new",
    createdAt: now,
    updatedAt: now
  };
  const runtimeReports = loadRuntimeReports();

  saveRuntimeReports([...runtimeReports, report]);

  return {
    ok: true,
    report
  };
}
